### ISSUE TITLE
Magnolia models throwing type error on missing value

### ISSUE THREAD

**Issue by matdenkas** [conrad-blucher-institute/semaphore#487]
magnolia_transform_48 - Oct 24 2024 06:22AM
Model failed to run due to semaphore error. Extra info provided: Error:: An unknown error ocurred!
<class 'TypeError'> semaphoreRunner.py 101
Traceback (most recent call last):
File "/app/src/semaphoreRunner.py", line 101, in run_semaphore
result = MW.make_prediction(executionTime)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/src/ModelExecution/modelWrapper.py", line 97, in make_prediction
inputs = self.inputGatherer.get_inputs(referenceTime)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/src/ModelExecution/inputGatherer.py", line 212, in get_inputs
self.post_process_data()
File "/app/src/ModelExecution/inputGatherer.py", line 144, in post_process_data
newProcessedInput = processing_Class.post_process_data(self.inputSeriesDict, postProcess)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/src/PostProcessing/PostProcessingClasses/MagnoliaPredictionsPostProcess.py", line 62, in post_process_data
transformed = float(magnolia_pred.dataValue) + average
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'

**Comment by matdenkas** [comment]
Tell Dr. Tissot who the problem ingestion class was
